- include: tasks/check.yaml

- name: disable SELinux
  selinux:
   state: disabled

- name: Install Zabbix Repo
  yum:
    name: https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present