- firewalld:
    service: http
    permanent: true
    immediate: yes
    state: enabled

- firewalld:
    port: 10051/tcp
    permanent: true
    immediate: yes
    state: enabled

- name: yum install phase1
  yum:
    name:
      - mariadb-server
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-apache-conf
      - zabbix-agent
      - epel-release
      - python3
      - python3-PyMySQL

- name: enabled and start mariadb
  service:
    name: mariadb
    state: started
    enabled: yes

- name: create database zabbix
  mysql_db:
    name: zabbix
    encoding: utf8
    state: present

- name: create and modify zabbix user
  mysql_user:
    name: zabbix
    password: "{{ item.zabbix_mariadb_password }}"
    priv: 'zabbix.*:ALL,GRANT'
    state: present
  with_items: "{{ zabbix_setup }}"

- name: check to exist  zabbix table. ignore status is OK.
  shell: mysql -u root -ss zabbix -e "select count(*) from users"
  ignore_errors: yes
  register: count_users
- debug: var=count_users

- name: insert zabbix DB
  shell: zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql zabbix -u root
  when: count_users.rc != 0

- name: modify httpd config
  lineinfile: >-
    dest='/etc/httpd/conf.d/zabbix.conf'
    state=present
    backrefs=yes
    regexp='php_value date.timezone'
    line='        php_value date.timezone Asia/Tokyo' 
  notify:
    - restart httpd

- name: enabled and start httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: modify config
  lineinfile: >-
    dest='/etc/zabbix/zabbix_server.conf'
    state=present
    backrefs=yes
    regexp='DBPassword=$'
    line="DBPassword={{ item.zabbix_mariadb_password }}"
  with_items: "{{ zabbix_setup }}"
  notify:
    - restart zabbix-server

- name: template zabbix.conf.php
  template: >
    src=zabbix.conf.php.j2
    dest=/etc/zabbix/web/zabbix.conf.php
    owner=root
    group=root
    mode=0644
  with_items: "{{ zabbix_setup }}"

- name: enabled and start zabbix-server
  service:
    name: zabbix-server
    state: started
    enabled: yes